### ISSUE TITLE
PostgreSQL Docker : FATAL: could not open directory "pg_notify": No such file or directory 

### ISSUE THREAD

**Issue by Etisti** [Aggarwal-Abhishek/Docker#1]
Hi i tried to run the app with docker-compose build up but i got the following messages error in docker logs : 

"
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-07-18 16:13:59.306 UTC [1] FATAL: could not open directory "pg_notify": No such file or directory

2021-07-18 16:13:59.308 UTC [1] LOG: database system is shut down
"

**Comment by Aggarwal-Abhishek** [comment]
Hi Etisti
Please delete the directory (**db_data**) before running **docker-compose up**.

After deleting, if you still get the same error it might be because the **api service** started early before the **database** is started, So it is unable to connect with **database service**.
In that case kindly stop the docker-compose using **(Ctrl+C)** and then run docker-compose again. It will start the second time.

**Comment by Etisti** [comment]
Thanks Aggarwal, it worked indeed, but how can we change this in order to not run docker-compose twice to make this work.... It is not really clean thought. Is there a way to change the compose file to make start the database service first and then when it's running starts the api service so it is certain it'll work ?

**Comment by Aggarwal-Abhishek** [comment]
You are right Etisti. I have resolved this issue.

1. In the docker-compose.yml you can see our **api** service depends on **database** service. So indeed the database service starts before but it just that when starting it the first time the database is not yet ready to receive connections request.
2. In that case we can either set a timeout in **api/DatabaseHandler.py** file or simple just retry connecting to database service until we receive the successful response.

Please see my changes in **api/DatabaseHandler.py** file basically the crux is 

```
while True:
    try:
        Try connecting to Database
        break if connected
    except:
        wait for 2 seconds
        continue the loop
```


It will work fine now. Please let me know if you face any issue.

**Comment by Etisti** [comment]
Indeed it solved the issue =] 

If you (or anyone) find an other better solution thought pleas comment below ^^

Thanks a lot =)
